package com.cmms.ai.entity;

public enum FailureAnalysisType {
    MANUFACTURER_DEPARTMENT_CONCENTRATION,
    MODEL_DEPARTMENT_CONCENTRATION,
    DEPARTMENT_ABNORMAL_CLAIM_RATE,
    CATEGORY_CONCENTRATION,
    SUPPLIER_CONCENTRATION,
    CRITICAL_EQUIPMENT_CLAIM_CLUSTER,
    OPEN_CLAIM_ACCUMULATION,
    HIGH_WORK_ORDER_CONVERSION,
    UNDER_REPAIR_AVAILABILITY_RISK,
    MAINTENANCE_COST_CONCENTRATION,
    SPARE_PART_USAGE_CONCENTRATION,
    EARLY_LIFE_EQUIPMENT_CLAIMS,
    WARRANTY_PERIOD_CLAIMS
}
