// Mock data for Hospital CMMS/GMAO

export const departments = [
  { id: "dept-1", name: "Radiology" },
  { id: "dept-2", name: "ICU" },
  { id: "dept-3", name: "Emergency" },
  { id: "dept-4", name: "Surgery" },
  { id: "dept-5", name: "Cardiology" },
  { id: "dept-6", name: "Pediatrics" },
]

export const equipment = [
  {
    id: "eq-001",
    name: "MRI Machine",
    serialNumber: "MRI-2024-001",
    classification: "Biomedical",
    criticality: "Critical",
    status: "Active",
    location: "Building A, Floor 2, Room 201",
    department: "Radiology",
    lastMaintenance: "2024-03-15",
    nextMaintenance: "2024-06-15",
    manufacturer: "Siemens",
    model: "MAGNETOM Vida",
    installDate: "2022-01-15",
    warrantyExpiry: "2027-01-15",
    operatingHours: 12450,
  },
  {
    id: "eq-002",
    name: "CT Scanner",
    serialNumber: "CT-2024-002",
    classification: "Biomedical",
    criticality: "Critical",
    status: "Active",
    location: "Building A, Floor 2, Room 205",
    department: "Radiology",
    lastMaintenance: "2024-03-10",
    nextMaintenance: "2024-06-10",
    manufacturer: "GE Healthcare",
    model: "Revolution CT",
    installDate: "2021-06-20",
    warrantyExpiry: "2026-06-20",
    operatingHours: 15230,
  },
  {
    id: "eq-003",
    name: "Ventilator Unit A",
    serialNumber: "VENT-2024-003",
    classification: "Biomedical",
    criticality: "Critical",
    status: "Active",
    location: "Building B, Floor 3, ICU Bay 1",
    department: "ICU",
    lastMaintenance: "2024-04-01",
    nextMaintenance: "2024-05-01",
    manufacturer: "Philips",
    model: "Trilogy Evo",
    installDate: "2023-02-10",
    warrantyExpiry: "2028-02-10",
    operatingHours: 8760,
  },
  {
    id: "eq-004",
    name: "Infusion Pump Station",
    serialNumber: "INF-2024-004",
    classification: "Biomedical",
    criticality: "High",
    status: "Active",
    location: "Building B, Floor 3, ICU Bay 2",
    department: "ICU",
    lastMaintenance: "2024-03-28",
    nextMaintenance: "2024-06-28",
    manufacturer: "Baxter",
    model: "Spectrum IQ",
    installDate: "2022-08-15",
    warrantyExpiry: "2027-08-15",
    operatingHours: 6540,
  },
  {
    id: "eq-005",
    name: "Autoclave Sterilizer",
    serialNumber: "AUTO-2024-005",
    classification: "Technical",
    criticality: "High",
    status: "Active",
    location: "Building C, Floor 1, Sterilization",
    department: "Surgery",
    lastMaintenance: "2024-03-20",
    nextMaintenance: "2024-04-20",
    manufacturer: "Steris",
    model: "AMSCO 400",
    installDate: "2020-11-05",
    warrantyExpiry: "2025-11-05",
    operatingHours: 18900,
  },
  {
    id: "eq-006",
    name: "HVAC Central Unit",
    serialNumber: "HVAC-2024-006",
    classification: "Technical",
    criticality: "High",
    status: "Active",
    location: "Building A, Basement, Mechanical",
    department: "Facilities",
    lastMaintenance: "2024-02-15",
    nextMaintenance: "2024-05-15",
    manufacturer: "Carrier",
    model: "AquaEdge 19DV",
    installDate: "2019-03-10",
    warrantyExpiry: "2024-03-10",
    operatingHours: 43800,
  },
  {
    id: "eq-007",
    name: "Emergency Generator",
    serialNumber: "GEN-2024-007",
    classification: "Technical",
    criticality: "Critical",
    status: "Active",
    location: "Building A, Basement, Power Room",
    department: "Facilities",
    lastMaintenance: "2024-04-05",
    nextMaintenance: "2024-07-05",
    manufacturer: "Caterpillar",
    model: "C18",
    installDate: "2018-07-20",
    warrantyExpiry: "2023-07-20",
    operatingHours: 520,
  },
  {
    id: "eq-008",
    name: "Nurse Station Server",
    serialNumber: "SRV-2024-008",
    classification: "IT",
    criticality: "Medium",
    status: "Active",
    location: "Building B, Floor 2, Server Room",
    department: "IT",
    lastMaintenance: "2024-03-01",
    nextMaintenance: "2024-09-01",
    manufacturer: "Dell",
    model: "PowerEdge R750",
    installDate: "2023-01-15",
    warrantyExpiry: "2028-01-15",
    operatingHours: 10950,
  },
  {
    id: "eq-009",
    name: "UPS System",
    serialNumber: "UPS-2024-009",
    classification: "Technical",
    criticality: "Critical",
    status: "Out of Service",
    location: "Building A, Basement, Power Room",
    department: "Facilities",
    lastMaintenance: "2024-01-20",
    nextMaintenance: "2024-04-20",
    manufacturer: "Eaton",
    model: "9395",
    installDate: "2017-05-10",
    warrantyExpiry: "2022-05-10",
    operatingHours: 61320,
  },
  {
    id: "eq-010",
    name: "Defibrillator",
    serialNumber: "DEF-2024-010",
    classification: "Biomedical",
    criticality: "Critical",
    status: "Active",
    location: "Building B, Floor 1, Emergency",
    department: "Emergency",
    lastMaintenance: "2024-04-08",
    nextMaintenance: "2024-05-08",
    manufacturer: "Zoll",
    model: "X Series",
    installDate: "2022-09-01",
    warrantyExpiry: "2027-09-01",
    operatingHours: 890,
  },
]

export const claims = [
  {
    id: "CLM-001",
    title: "MRI Machine Unusual Noise",
    equipment: "MRI Machine",
    equipmentId: "eq-001",
    description: "Unusual grinding noise during operation. Patient safety concern.",
    priority: "Critical",
    status: "In Progress",
    createdBy: "Dr. Sarah Johnson",
    createdAt: "2024-04-10T09:30:00",
    assignedTo: "John Smith",
    department: "Radiology",
    site: "Central Hospital",
  },
  {
    id: "CLM-002",
    title: "Ventilator Alarm Malfunction",
    equipment: "Ventilator Unit A",
    equipmentId: "eq-003",
    description: "Alarm not triggering at set parameters. Critical for patient monitoring.",
    priority: "Critical",
    status: "Qualified",
    createdBy: "Nurse Amy Chen",
    createdAt: "2024-04-10T08:15:00",
    assignedTo: null,
    department: "ICU",
    site: "Central Hospital",
  },
  {
    id: "CLM-003",
    title: "HVAC Temperature Inconsistency",
    equipment: "HVAC Central Unit",
    equipmentId: "eq-006",
    description: "Temperature fluctuating in surgery wing. Affecting OR conditions.",
    priority: "High",
    status: "Assigned",
    createdBy: "Dr. Michael Brown",
    createdAt: "2024-04-09T14:20:00",
    assignedTo: "Robert Davis",
    department: "Surgery",
    site: "North Medical Center",
  },
  {
    id: "CLM-004",
    title: "Infusion Pump Display Issue",
    equipment: "Infusion Pump Station",
    equipmentId: "eq-004",
    description: "Display flickering intermittently. Difficult to read dosage.",
    priority: "Medium",
    status: "Open",
    createdBy: "Nurse Tom Wilson",
    createdAt: "2024-04-09T11:45:00",
    assignedTo: null,
    department: "ICU",
    site: "Central Hospital",
  },
  {
    id: "CLM-005",
    title: "Server Performance Degradation",
    equipment: "Nurse Station Server",
    equipmentId: "eq-008",
    description: "Server response time increased. Affecting patient record access.",
    priority: "Medium",
    status: "Closed",
    createdBy: "IT Support",
    createdAt: "2024-04-08T16:30:00",
    assignedTo: "Alex Thompson",
    department: "IT",
    site: "Central Hospital",
  },
]

export const workOrders = [
  {
    id: "WO-001",
    title: "MRI Machine Emergency Repair",
    equipment: "MRI Machine",
    equipmentId: "eq-001",
    type: "Corrective",
    priority: "Critical",
    status: "In Progress",
    assignedTo: "John Smith",
    estimatedTime: 4,
    actualTime: 2.5,
    estimatedCost: 5000,
    actualCost: 3200,
    createdAt: "2024-04-10T10:00:00",
    dueDate: "2024-04-10T18:00:00",
    department: "Radiology",
    site: "Central Hospital",
    claimId: "CLM-001",
  },
  {
    id: "WO-002",
    title: "CT Scanner Quarterly Maintenance",
    equipment: "CT Scanner",
    equipmentId: "eq-002",
    type: "Preventive",
    priority: "Medium",
    status: "Scheduled",
    assignedTo: "Jane Doe",
    estimatedTime: 6,
    actualTime: null,
    estimatedCost: 2500,
    actualCost: null,
    createdAt: "2024-04-08T09:00:00",
    dueDate: "2024-04-15T17:00:00",
    department: "Radiology",
    site: "Central Hospital",
    claimId: null,
  },
  {
    id: "WO-003",
    title: "Autoclave Regulatory Inspection",
    equipment: "Autoclave Sterilizer",
    equipmentId: "eq-005",
    type: "Regulatory",
    priority: "High",
    status: "Scheduled",
    assignedTo: "Robert Davis",
    estimatedTime: 3,
    actualTime: null,
    estimatedCost: 1200,
    actualCost: null,
    createdAt: "2024-04-07T14:00:00",
    dueDate: "2024-04-12T12:00:00",
    department: "Surgery",
    site: "North Medical Center",
    claimId: null,
  },
  {
    id: "WO-004",
    title: "Generator Monthly Check",
    equipment: "Emergency Generator",
    equipmentId: "eq-007",
    type: "Preventive",
    priority: "High",
    status: "Completed",
    assignedTo: "Mike Johnson",
    estimatedTime: 2,
    actualTime: 1.5,
    estimatedCost: 800,
    actualCost: 650,
    createdAt: "2024-04-05T08:00:00",
    dueDate: "2024-04-05T12:00:00",
    department: "Facilities",
    site: "Central Hospital",
    claimId: null,
  },
  {
    id: "WO-005",
    title: "UPS Battery Replacement",
    equipment: "UPS System",
    equipmentId: "eq-009",
    type: "Corrective",
    priority: "Critical",
    status: "In Progress",
    assignedTo: "John Smith",
    estimatedTime: 5,
    actualTime: 3,
    estimatedCost: 8000,
    actualCost: 7500,
    createdAt: "2024-04-09T07:00:00",
    dueDate: "2024-04-11T17:00:00",
    department: "Facilities",
    site: "Central Hospital",
    claimId: null,
  },
]

export const technicians = [
  { id: "tech-1", name: "John Smith", specialization: "Biomedical", workload: 85 },
  { id: "tech-2", name: "Jane Doe", specialization: "Biomedical", workload: 60 },
  { id: "tech-3", name: "Robert Davis", specialization: "Technical", workload: 75 },
  { id: "tech-4", name: "Mike Johnson", specialization: "Technical", workload: 45 },
  { id: "tech-5", name: "Alex Thompson", specialization: "IT", workload: 50 },
]

export const spareParts = [
  {
    id: "part-001",
    name: "MRI Cooling Fan",
    sku: "MRI-FAN-001",
    category: "Biomedical",
    quantity: 5,
    minStock: 3,
    unitCost: 450,
    location: "Warehouse A, Shelf 12",
    supplier: "Siemens Parts",
  },
  {
    id: "part-002",
    name: "CT X-Ray Tube",
    sku: "CT-TUBE-001",
    category: "Biomedical",
    quantity: 2,
    minStock: 2,
    unitCost: 15000,
    location: "Warehouse A, Shelf 15",
    supplier: "GE Healthcare Parts",
  },
  {
    id: "part-003",
    name: "Ventilator Filter",
    sku: "VENT-FILT-001",
    category: "Biomedical",
    quantity: 50,
    minStock: 20,
    unitCost: 25,
    location: "Warehouse B, Shelf 3",
    supplier: "Philips Medical",
  },
  {
    id: "part-004",
    name: "HVAC Compressor",
    sku: "HVAC-COMP-001",
    category: "Technical",
    quantity: 1,
    minStock: 2,
    unitCost: 3500,
    location: "Warehouse A, Shelf 8",
    supplier: "Carrier Parts",
  },
  {
    id: "part-005",
    name: "UPS Battery Pack",
    sku: "UPS-BAT-001",
    category: "Technical",
    quantity: 4,
    minStock: 4,
    unitCost: 1200,
    location: "Warehouse A, Shelf 10",
    supplier: "Eaton Power",
  },
  {
    id: "part-006",
    name: "Server SSD Drive",
    sku: "SRV-SSD-001",
    category: "IT",
    quantity: 10,
    minStock: 5,
    unitCost: 350,
    location: "Warehouse B, Shelf 1",
    supplier: "Dell Technologies",
  },
]

export const kpiData = {
  mtbf: 720, // hours
  mttr: 4.5, // hours
  availabilityRate: 98.5, // percentage
  correctivePreventiveRatio: 0.35, // 35% corrective, 65% preventive
  costPerEquipment: 2450, // USD
  costPerService: 12500, // USD
  totalEquipment: 156,
  activeWorkOrders: 24,
  pendingClaims: 8,
  criticalAlerts: 3,
}

export const monthlyTrends = [
  { month: "Jan", mtbf: 680, mttr: 5.2, availability: 97.8, cost: 45000 },
  { month: "Feb", mtbf: 695, mttr: 4.8, availability: 98.1, cost: 42000 },
  { month: "Mar", mtbf: 710, mttr: 4.6, availability: 98.3, cost: 38000 },
  { month: "Apr", mtbf: 720, mttr: 4.5, availability: 98.5, cost: 35000 },
  { month: "May", mtbf: 735, mttr: 4.3, availability: 98.7, cost: 33000 },
  { month: "Jun", mtbf: 750, mttr: 4.1, availability: 98.9, cost: 31000 },
]

export const costByDepartment = [
  { department: "Radiology", cost: 85000, percentage: 28 },
  { department: "ICU", cost: 65000, percentage: 21 },
  { department: "Surgery", cost: 55000, percentage: 18 },
  { department: "Emergency", cost: 45000, percentage: 15 },
  { department: "Facilities", cost: 35000, percentage: 11 },
  { department: "IT", cost: 20000, percentage: 7 },
]

export const maintenanceDistribution = [
  { type: "Preventive", count: 145, percentage: 58 },
  { type: "Corrective", count: 75, percentage: 30 },
  { type: "Regulatory", count: 20, percentage: 8 },
  { type: "Predictive", count: 10, percentage: 4 },
]

export const aiPredictions = [
  {
    id: "pred-001",
    equipment: "MRI Machine",
    equipmentId: "eq-001",
    riskScore: 78,
    riskLevel: "High",
    recommendation: "Schedule preventive maintenance within 2 weeks",
    factors: ["High operating hours", "Previous failure pattern", "Critical equipment"],
  },
  {
    id: "pred-002",
    equipment: "HVAC Central Unit",
    equipmentId: "eq-006",
    riskScore: 65,
    riskLevel: "Medium",
    recommendation: "Monitor closely, consider filter replacement",
    factors: ["Age factor", "Seasonal load increase", "Minor efficiency drop"],
  },
  {
    id: "pred-003",
    equipment: "UPS System",
    equipmentId: "eq-009",
    riskScore: 92,
    riskLevel: "Critical",
    recommendation: "Immediate intervention required - battery replacement",
    factors: ["Battery degradation", "Multiple recent alarms", "End of lifecycle"],
  },
  {
    id: "pred-004",
    equipment: "Autoclave Sterilizer",
    equipmentId: "eq-005",
    riskScore: 45,
    riskLevel: "Low",
    recommendation: "Continue regular maintenance schedule",
    factors: ["Good operating condition", "Recent maintenance completed"],
  },
]

export const auditLogs = [
  {
    id: "audit-001",
    action: "Work Order Created",
    user: "John Smith",
    role: "Technician",
    timestamp: "2024-04-10T10:30:00",
    details: "Created WO-001 for MRI Machine Emergency Repair",
    ip: "192.168.1.45",
  },
  {
    id: "audit-002",
    action: "Equipment Status Changed",
    user: "Admin User",
    role: "Administrator",
    timestamp: "2024-04-10T09:15:00",
    details: "Changed UPS System status to Out of Service",
    ip: "192.168.1.10",
  },
  {
    id: "audit-003",
    action: "Claim Qualified",
    user: "Jane Doe",
    role: "Maintenance Manager",
    timestamp: "2024-04-10T08:45:00",
    details: "Qualified CLM-002 as Critical priority",
    ip: "192.168.1.22",
  },
  {
    id: "audit-004",
    action: "User Login",
    user: "Dr. Sarah Johnson",
    role: "Hospital Staff",
    timestamp: "2024-04-10T08:00:00",
    details: "Successful login from hospital network",
    ip: "192.168.1.78",
  },
  {
    id: "audit-005",
    action: "Report Exported",
    user: "Finance Director",
    role: "Direction/Finance",
    timestamp: "2024-04-09T16:30:00",
    details: "Exported Q1 maintenance cost report to PDF",
    ip: "192.168.1.55",
  },
]

export const users = [
  {
    id: "user-001",
    name: "Admin User",
    email: "admin@hospital.com",
    role: "Administrator",
    department: "IT",
    status: "Active",
    lastLogin: "2024-04-10T09:00:00",
  },
  {
    id: "user-002",
    name: "Jane Doe",
    email: "jane.doe@hospital.com",
    role: "Maintenance Manager",
    department: "Maintenance",
    status: "Active",
    lastLogin: "2024-04-10T08:30:00",
  },
  {
    id: "user-003",
    name: "John Smith",
    email: "john.smith@hospital.com",
    role: "Technician",
    department: "Maintenance",
    status: "Active",
    lastLogin: "2024-04-10T07:45:00",
  },
  {
    id: "user-004",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@hospital.com",
    role: "Hospital Staff",
    department: "Radiology",
    status: "Active",
    lastLogin: "2024-04-10T08:00:00",
  },
  {
    id: "user-005",
    name: "Finance Director",
    email: "finance@hospital.com",
    role: "Direction/Finance",
    department: "Finance",
    status: "Active",
    lastLogin: "2024-04-09T16:00:00",
  },
]

export const notifications = [
  {
    id: "notif-001",
    title: "Critical Alert",
    message: "UPS System requires immediate attention",
    type: "critical",
    read: false,
    timestamp: "2024-04-10T10:30:00",
  },
  {
    id: "notif-002",
    title: "Work Order Assigned",
    message: "WO-001 has been assigned to you",
    type: "info",
    read: false,
    timestamp: "2024-04-10T10:00:00",
  },
  {
    id: "notif-003",
    title: "Maintenance Due",
    message: "CT Scanner quarterly maintenance is due in 5 days",
    type: "warning",
    read: true,
    timestamp: "2024-04-10T09:00:00",
  },
  {
    id: "notif-004",
    title: "Low Stock Alert",
    message: "HVAC Compressor stock is below minimum",
    type: "warning",
    read: true,
    timestamp: "2024-04-09T14:00:00",
  },
]

export const calendarEvents = [
  {
    id: "event-001",
    title: "MRI Preventive Maintenance",
    start: "2024-04-15T08:00:00",
    end: "2024-04-15T12:00:00",
    type: "preventive",
    equipment: "MRI Machine",
    technician: "John Smith",
  },
  {
    id: "event-002",
    title: "CT Scanner Maintenance",
    start: "2024-04-15T13:00:00",
    end: "2024-04-15T17:00:00",
    type: "preventive",
    equipment: "CT Scanner",
    technician: "Jane Doe",
  },
  {
    id: "event-003",
    title: "Autoclave Inspection",
    start: "2024-04-12T09:00:00",
    end: "2024-04-12T12:00:00",
    type: "regulatory",
    equipment: "Autoclave Sterilizer",
    technician: "Robert Davis",
  },
  {
    id: "event-004",
    title: "HVAC Filter Replacement",
    start: "2024-04-18T08:00:00",
    end: "2024-04-18T10:00:00",
    type: "preventive",
    equipment: "HVAC Central Unit",
    technician: "Mike Johnson",
  },
  {
    id: "event-005",
    title: "Generator Test Run",
    start: "2024-04-20T06:00:00",
    end: "2024-04-20T08:00:00",
    type: "regulatory",
    equipment: "Emergency Generator",
    technician: "Mike Johnson",
  },
]
